// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {update_svc} from '../models';
import {app} from '../models';
import {policy_group_entity} from '../models';
import {asset_entity} from '../models';
import {conversation_entity} from '../models';
import {forward_entity} from '../models';
import {group_entity} from '../models';
import {credential_entity} from '../models';
import {snippet_svc} from '../models';
import {snippet_entity} from '../models';
import {backup_svc} from '../models';
import {query_svc} from '../models';
import {extension_svc} from '../models';
import {extension} from '../models';
import {sshpool} from '../models';
import {ssh_svc} from '../models';
import {status} from '../models';
import {import_svc} from '../models';
import {kafka_svc} from '../models';
import {audit_repo} from '../models';
import {redis_svc} from '../models';
import {ai} from '../models';
import {sftp_svc} from '../models';
import {context} from '../models';

export function CallExtensionAction(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CallExtensionTool(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CancelExtensionAction(arg1:string):Promise<void>;

export function CancelGitHubAuth():Promise<void>;

export function CancelSSHConnect(arg1:string):Promise<void>;

export function CancelTest(arg1:string):Promise<void>;

export function ChangeSSHDirectory(arg1:string,arg2:string):Promise<void>;

export function CheckForUpdate():Promise<update_svc.UpdateInfo>;

export function Cleanup():Promise<void>;

export function ClearGitHubToken():Promise<void>;

export function ClearQueuedAIMessages(arg1:number):Promise<Array<string>>;

export function ClearWebDAVConfig():Promise<void>;

export function ConnectSSH(arg1:app.SSHConnectRequest):Promise<string>;

export function ConnectSSHAsync(arg1:app.SSHConnectRequest):Promise<string>;

export function CopyPolicyGroup(arg1:string,arg2:string):Promise<policy_group_entity.PolicyGroup>;

export function CreateAIProvider(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number,arg7:number,arg8:boolean,arg9:string):Promise<app.AIProviderInfo>;

export function CreateAsset(arg1:asset_entity.Asset):Promise<void>;

export function CreateConversation():Promise<conversation_entity.Conversation>;

export function CreateForwardConfig(arg1:string,arg2:number,arg3:Array<forward_entity.ForwardRule>):Promise<forward_entity.ForwardConfig>;

export function CreateGroup(arg1:group_entity.Group):Promise<void>;

export function CreatePasswordCredential(arg1:string,arg2:string,arg3:string,arg4:string):Promise<credential_entity.Credential>;

export function CreatePolicyGroup(arg1:policy_group_entity.PolicyGroup):Promise<policy_group_entity.PolicyGroup>;

export function CreateSnippet(arg1:snippet_svc.CreateReq):Promise<snippet_entity.Snippet>;

export function DeleteAIProvider(arg1:number):Promise<void>;

export function DeleteAsset(arg1:number):Promise<void>;

export function DeleteConversation(arg1:number):Promise<void>;

export function DeleteCredential(arg1:number):Promise<void>;

export function DeleteForwardConfig(arg1:number):Promise<void>;

export function DeleteGroup(arg1:number,arg2:boolean):Promise<void>;

export function DeletePolicyGroup(arg1:string):Promise<void>;

export function DeleteSnippet(arg1:number):Promise<void>;

export function DetectOpsctl():Promise<app.OpsctlInfo>;

export function DetectSkills():Promise<Array<app.SkillTarget>>;

export function DisableExtension(arg1:string):Promise<void>;

export function DisconnectSSH(arg1:string):Promise<void>;

export function DownloadAndInstallUpdate(arg1:boolean):Promise<void>;

export function DrainAIFlushAck():Promise<void>;

export function DuplicateSnippet(arg1:number):Promise<snippet_entity.Snippet>;

export function EnableExtension(arg1:string):Promise<void>;

export function EnableSSHSync(arg1:string):Promise<void>;

export function EncryptPassword(arg1:string):Promise<string>;

export function ExecuteImportFile(arg1:string,arg2:string,arg3:backup_svc.ImportOptions):Promise<backup_svc.ImportResult>;

export function ExecuteMongo(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function ExecuteRedis(arg1:number,arg2:string,arg3:number):Promise<string>;

export function ExecuteRedisArgs(arg1:number,arg2:Array<string>,arg3:number):Promise<string>;

export function ExecuteSQL(arg1:number,arg2:string,arg3:string):Promise<string>;

export function ExecuteSQLPaged(arg1:number,arg2:string,arg3:string,arg4:number,arg5:number):Promise<string>;

export function ExecuteTableImport(arg1:number,arg2:string,arg3:query_svc.TableImportBatchRequest):Promise<query_svc.TableImportBatchResult>;

export function ExportData():Promise<string>;

export function ExportToFile(arg1:string,arg2:backup_svc.ExportOptions):Promise<void>;

export function ExportToGist(arg1:string,arg2:string,arg3:string,arg4:backup_svc.ExportOptions):Promise<backup_svc.GistInfo>;

export function ExportToWebDAV(arg1:string,arg2:backup_svc.ExportOptions):Promise<backup_svc.WebDAVBackupInfo>;

export function FetchAIModels(arg1:string,arg2:string,arg3:string):Promise<Array<app.AIModelInfo>>;

export function ForceUninstallExtension(arg1:string,arg2:boolean):Promise<void>;

export function GenerateSSHKey(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string,arg6:string):Promise<credential_entity.Credential>;

export function GetActiveAIProvider():Promise<app.AIProviderInfo>;

export function GetAppVersion():Promise<string>;

export function GetAsset(arg1:number):Promise<asset_entity.Asset>;

export function GetAssetPassword(arg1:number):Promise<string>;

export function GetAvailableAssetTypes():Promise<Array<app.AssetTypeInfo>>;

export function GetAvailableMirrors():Promise<Array<update_svc.MirrorInfo>>;

export function GetBugReportInfo():Promise<app.BugReportInfo>;

export function GetCredentialPublicKey(arg1:number):Promise<string>;

export function GetCredentialUsage(arg1:number):Promise<Array<string>>;

export function GetCurrentConversationID():Promise<number>;

export function GetDataDir():Promise<string>;

export function GetDebugMode():Promise<boolean>;

export function GetDecryptedExtensionConfig(arg1:number,arg2:string):Promise<string>;

export function GetDefaultPolicy(arg1:string):Promise<string>;

export function GetDownloadMirror():Promise<string>;

export function GetExtensionDetail(arg1:string):Promise<extension_svc.ExtensionInfo>;

export function GetExtensionManifest(arg1:string):Promise<extension.Manifest>;

export function GetGitHubToken():Promise<string>;

export function GetGitHubUser(arg1:string):Promise<backup_svc.GitHubUser>;

export function GetGroup(arg1:number):Promise<group_entity.Group>;

export function GetK8sClusterInfo(arg1:number):Promise<string>;

export function GetK8sNamespaceConfigMaps(arg1:number,arg2:string):Promise<string>;

export function GetK8sNamespaceDeployments(arg1:number,arg2:string):Promise<string>;

export function GetK8sNamespacePods(arg1:number,arg2:string):Promise<string>;

export function GetK8sNamespaceResources(arg1:number,arg2:string):Promise<string>;

export function GetK8sNamespaceSecrets(arg1:number,arg2:string):Promise<string>;

export function GetK8sNamespaceServices(arg1:number,arg2:string):Promise<string>;

export function GetK8sPodDetail(arg1:number,arg2:string,arg3:string):Promise<string>;

export function GetLanguage():Promise<string>;

export function GetModelDefaults(arg1:string):Promise<app.AIModelInfo>;

export function GetOpsctlInstallDir():Promise<string>;

export function GetPluginReferenceDir():Promise<string>;

export function GetSSHPoolConnections():Promise<Array<sshpool.PoolEntryInfo>>;

export function GetSSHSyncState(arg1:string):Promise<ssh_svc.DirectorySyncState>;

export function GetSkillPreview():Promise<string>;

export function GetSnippet(arg1:number):Promise<snippet_entity.Snippet>;

export function GetSnippetLastAssets(arg1:number):Promise<Array<number>>;

export function GetStoredGitHubUser():Promise<string>;

export function GetSystemStatus():Promise<Array<status.Entry>>;

export function GetUpdateChannel():Promise<string>;

export function GetWebDAVConfig():Promise<app.WebDAVStoredConfig>;

export function ImportFromGist(arg1:string,arg2:string,arg3:string,arg4:backup_svc.ImportOptions):Promise<backup_svc.ImportResult>;

export function ImportFromWebDAV(arg1:string,arg2:string,arg3:backup_svc.ImportOptions):Promise<backup_svc.ImportResult>;

export function ImportSSHConfigSelected(arg1:Array<number>,arg2:boolean):Promise<import_svc.ImportResult>;

export function ImportSSHKeyFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<credential_entity.Credential>;

export function ImportSSHKeyPEM(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<credential_entity.Credential>;

export function ImportTabbySelected(arg1:Array<number>,arg2:string,arg3:boolean):Promise<import_svc.ImportResult>;

export function InitAIProvider():Promise<void>;

export function InstallExtension():Promise<extension_svc.ExtensionInfo>;

export function InstallExtensionFromDirectory():Promise<extension_svc.ExtensionInfo>;

export function InstallOpsctl(arg1:string):Promise<string>;

export function InstallSkills():Promise<void>;

export function KafkaAlterTopicConfig(arg1:kafka_svc.AlterTopicConfigRequest):Promise<kafka_svc.TopicOperationResponse>;

export function KafkaBrowseMessages(arg1:kafka_svc.BrowseMessagesRequest):Promise<kafka_svc.BrowseMessagesResponse>;

export function KafkaCheckSchemaCompatibility(arg1:kafka_svc.CheckSchemaCompatibilityRequest):Promise<kafka_svc.CheckSchemaCompatibilityResponse>;

export function KafkaClusterOverview(arg1:number):Promise<kafka_svc.ClusterOverview>;

export function KafkaCreateACL(arg1:kafka_svc.CreateACLRequest):Promise<kafka_svc.ACLMutationResponse>;

export function KafkaCreateConnector(arg1:kafka_svc.ConnectorConfigRequest):Promise<kafka_svc.ConnectorOperationResponse>;

export function KafkaCreateTopic(arg1:kafka_svc.CreateTopicRequest):Promise<kafka_svc.TopicOperationResponse>;

export function KafkaDeleteACL(arg1:kafka_svc.DeleteACLRequest):Promise<kafka_svc.ACLMutationResponse>;

export function KafkaDeleteConnector(arg1:number,arg2:string,arg3:string):Promise<kafka_svc.ConnectorOperationResponse>;

export function KafkaDeleteConsumerGroup(arg1:number,arg2:string):Promise<kafka_svc.DeleteConsumerGroupResponse>;

export function KafkaDeleteRecords(arg1:kafka_svc.DeleteRecordsRequest):Promise<kafka_svc.DeleteRecordsResponse>;

export function KafkaDeleteSchema(arg1:kafka_svc.DeleteSchemaRequest):Promise<kafka_svc.DeleteSchemaResponse>;

export function KafkaDeleteTopic(arg1:number,arg2:string):Promise<kafka_svc.TopicOperationResponse>;

export function KafkaGetBrokerConfig(arg1:number,arg2:number):Promise<kafka_svc.BrokerConfigResponse>;

export function KafkaGetConnector(arg1:number,arg2:string,arg3:string):Promise<kafka_svc.KafkaConnectorDetail>;

export function KafkaGetConsumerGroup(arg1:number,arg2:string):Promise<kafka_svc.ConsumerGroupDetail>;

export function KafkaGetSchema(arg1:number,arg2:string,arg3:string):Promise<kafka_svc.SchemaVersionDetail>;

export function KafkaGetSchemaSubjectVersions(arg1:number,arg2:string):Promise<kafka_svc.SchemaSubjectVersions>;

export function KafkaGetTopic(arg1:number,arg2:string):Promise<kafka_svc.TopicDetail>;

export function KafkaIncreasePartitions(arg1:kafka_svc.IncreasePartitionsRequest):Promise<kafka_svc.TopicOperationResponse>;

export function KafkaListACLs(arg1:kafka_svc.ListACLsRequest):Promise<kafka_svc.ListACLsResponse>;

export function KafkaListBrokers(arg1:number):Promise<Array<kafka_svc.Broker>>;

export function KafkaListClusterConfigs(arg1:number):Promise<kafka_svc.ClusterConfigsResponse>;

export function KafkaListConnectClusters(arg1:number):Promise<Array<kafka_svc.KafkaConnectCluster>>;

export function KafkaListConnectors(arg1:kafka_svc.ListConnectorsRequest):Promise<Array<kafka_svc.KafkaConnectorSummary>>;

export function KafkaListConsumerGroups(arg1:number):Promise<Array<kafka_svc.ConsumerGroup>>;

export function KafkaListSchemaSubjects(arg1:number):Promise<Array<string>>;

export function KafkaListTopics(arg1:kafka_svc.ListTopicsRequest):Promise<kafka_svc.ListTopicsResponse>;

export function KafkaPauseConnector(arg1:number,arg2:string,arg3:string):Promise<kafka_svc.ConnectorOperationResponse>;

export function KafkaProduceMessage(arg1:kafka_svc.ProduceMessageRequest):Promise<kafka_svc.ProduceMessageResponse>;

export function KafkaRegisterSchema(arg1:kafka_svc.RegisterSchemaRequest):Promise<kafka_svc.RegisterSchemaResponse>;

export function KafkaResetConsumerGroupOffset(arg1:kafka_svc.ResetConsumerGroupOffsetRequest):Promise<kafka_svc.ResetConsumerGroupOffsetResponse>;

export function KafkaRestartConnector(arg1:kafka_svc.RestartConnectorRequest):Promise<kafka_svc.ConnectorOperationResponse>;

export function KafkaResumeConnector(arg1:number,arg2:string,arg3:string):Promise<kafka_svc.ConnectorOperationResponse>;

export function KafkaUpdateConnectorConfig(arg1:kafka_svc.ConnectorConfigRequest):Promise<kafka_svc.ConnectorOperationResponse>;

export function ListAIProviders():Promise<Array<app.AIProviderInfo>>;

export function ListAssets(arg1:string,arg2:number):Promise<Array<asset_entity.Asset>>;

export function ListAuditLogs(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number,arg6:number,arg7:string):Promise<app.AuditLogListResult>;

export function ListAuditSessions(arg1:number):Promise<Array<audit_repo.SessionInfo>>;

export function ListBackupGists(arg1:string):Promise<Array<backup_svc.GistInfo>>;

export function ListConversations():Promise<Array<conversation_entity.Conversation>>;

export function ListCredentials():Promise<Array<credential_entity.Credential>>;

export function ListCredentialsByType(arg1:string):Promise<Array<credential_entity.Credential>>;

export function ListForwardConfigs():Promise<Array<app.ForwardConfigWithStatus>>;

export function ListGroups():Promise<Array<group_entity.Group>>;

export function ListInstalledExtensions():Promise<Array<extension_svc.ExtensionInfo>>;

export function ListLocalSSHKeys():Promise<Array<app.LocalSSHKeyInfo>>;

export function ListMongoCollections(arg1:number,arg2:string):Promise<string>;

export function ListMongoDatabases(arg1:number):Promise<string>;

export function ListPolicyGroups(arg1:string):Promise<Array<policy_group_entity.PolicyGroupItem>>;

export function ListSnippetCategories():Promise<Array<snippet_svc.Category>>;

export function ListSnippets(arg1:snippet_svc.ListReq):Promise<Array<snippet_entity.Snippet>>;

export function ListWebDAVBackups():Promise<Array<backup_svc.WebDAVBackupInfo>>;

export function LoadConversationMessages(arg1:number):Promise<Array<app.ConversationDisplayMessage>>;

export function MoveAsset(arg1:number,arg2:string):Promise<void>;

export function MoveGroup(arg1:number,arg2:string):Promise<void>;

export function OnSecondInstanceLaunch():Promise<void>;

export function OpenDirectory(arg1:string):Promise<void>;

export function OpenLogsDir():Promise<void>;

export function PreviewGistBackup(arg1:string,arg2:string,arg3:string):Promise<backup_svc.BackupSummary>;

export function PreviewImportFile(arg1:string,arg2:string):Promise<backup_svc.BackupSummary>;

export function PreviewSSHConfig():Promise<import_svc.PreviewResult>;

export function PreviewTabbyConfig():Promise<import_svc.PreviewResult>;

export function QueueAIMessage(arg1:number,arg2:string,arg3:string):Promise<void>;

export function RecordSnippetUse(arg1:number):Promise<void>;

export function RedisClientList(arg1:number):Promise<string>;

export function RedisCommandHistory(arg1:number,arg2:number):Promise<Array<redis_svc.CommandHistoryEntry>>;

export function RedisDeleteKeys(arg1:number,arg2:number,arg3:Array<string>):Promise<void>;

export function RedisEncodeValue(arg1:string,arg2:string):Promise<string>;

export function RedisFormatValue(arg1:string,arg2:string):Promise<redis_svc.RedisFormattedValue>;

export function RedisGetKeyDetail(arg1:redis_svc.RedisKeyRequest):Promise<redis_svc.RedisKeyDetail>;

export function RedisHashDelete(arg1:number,arg2:number,arg3:string,arg4:string):Promise<void>;

export function RedisHashSet(arg1:number,arg2:number,arg3:string,arg4:string,arg5:string):Promise<void>;

export function RedisListDatabases(arg1:number):Promise<Array<redis_svc.RedisDatabase>>;

export function RedisListDelete(arg1:number,arg2:number,arg3:string,arg4:number):Promise<void>;

export function RedisListPush(arg1:number,arg2:number,arg3:string,arg4:string):Promise<void>;

export function RedisListSet(arg1:number,arg2:number,arg3:string,arg4:number,arg5:string):Promise<void>;

export function RedisPersistKey(arg1:number,arg2:number,arg3:string):Promise<void>;

export function RedisRenameKey(arg1:number,arg2:number,arg3:string,arg4:string):Promise<void>;

export function RedisScanKeys(arg1:redis_svc.RedisScanRequest):Promise<redis_svc.RedisScanResponse>;

export function RedisSetAdd(arg1:number,arg2:number,arg3:string,arg4:string):Promise<void>;

export function RedisSetKeyTTL(arg1:number,arg2:number,arg3:string,arg4:number):Promise<void>;

export function RedisSetRemove(arg1:number,arg2:number,arg3:string,arg4:string):Promise<void>;

export function RedisSetStringValue(arg1:redis_svc.RedisStringSetRequest):Promise<void>;

export function RedisSlowLog(arg1:number,arg2:number):Promise<Array<redis_svc.RedisSlowLogEntry>>;

export function RedisStreamAdd(arg1:number,arg2:number,arg3:string,arg4:string,arg5:Array<redis_svc.RedisStreamField>):Promise<void>;

export function RedisStreamDelete(arg1:number,arg2:number,arg3:string,arg4:Array<string>):Promise<void>;

export function RedisZSetAdd(arg1:number,arg2:number,arg3:string,arg4:string,arg5:number):Promise<void>;

export function RedisZSetRemove(arg1:number,arg2:number,arg3:string,arg4:string):Promise<void>;

export function ReloadExtensions():Promise<void>;

export function RemoveQueuedAIMessage(arg1:number,arg2:string):Promise<boolean>;

export function ReorderAsset(arg1:number,arg2:number,arg3:number):Promise<void>;

export function ReorderGroup(arg1:number,arg2:number,arg3:number):Promise<void>;

export function ResizeSSH(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RespondAIApproval(arg1:string,arg2:ai.ApprovalResponse):Promise<void>;

export function RespondAuthChallenge(arg1:string,arg2:Array<string>):Promise<void>;

export function RespondHostKeyVerify(arg1:string,arg2:number):Promise<void>;

export function RespondOpsctlApproval(arg1:string,arg2:ai.ApprovalResponse):Promise<void>;

export function RespondPermission(arg1:string,arg2:string):Promise<void>;

export function SFTPCancelTransfer(arg1:string):Promise<void>;

export function SFTPChmod(arg1:string,arg2:string,arg3:number,arg4:boolean):Promise<void>;

export function SFTPCreateFile(arg1:string,arg2:string):Promise<void>;

export function SFTPDelete(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SFTPDownload(arg1:string,arg2:string):Promise<string>;

export function SFTPDownloadDir(arg1:string,arg2:string):Promise<string>;

export function SFTPGetwd(arg1:string):Promise<string>;

export function SFTPListDir(arg1:string,arg2:string):Promise<Array<sftp_svc.FileEntry>>;

export function SFTPMkdir(arg1:string,arg2:string):Promise<void>;

export function SFTPRename(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SFTPStat(arg1:string,arg2:string):Promise<sftp_svc.FileEntry>;

export function SFTPUpload(arg1:string,arg2:string):Promise<string>;

export function SFTPUploadDir(arg1:string,arg2:string):Promise<string>;

export function SFTPUploadFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveConversationMessages(arg1:number,arg2:Array<app.ConversationDisplayMessage>):Promise<void>;

export function SaveGitHubToken(arg1:string,arg2:string):Promise<void>;

export function SaveWebDAVConfig(arg1:app.WebDAVSaveInput):Promise<void>;

export function SelectImportFile():Promise<app.ImportFileInfo>;

export function SelectSSHKeyFile():Promise<app.LocalSSHKeyInfo>;

export function SelectTableExportFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SendAIMessage(arg1:number,arg2:Array<ai.Message>,arg3:ai.AIContext):Promise<void>;

export function SetActiveAIProvider(arg1:number):Promise<void>;

export function SetDebugMode(arg1:boolean):Promise<void>;

export function SetDownloadMirror(arg1:string):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetSnippetLastAssets(arg1:number,arg2:Array<number>):Promise<void>;

export function SetUpdateChannel(arg1:string):Promise<void>;

export function SplitSSH(arg1:string,arg2:number,arg3:number):Promise<string>;

export function StartForwardConfig(arg1:number):Promise<void>;

export function StartGitHubDeviceFlow():Promise<backup_svc.DeviceFlowInfo>;

export function StartK8sPodLogs(arg1:number,arg2:string,arg3:string,arg4:string,arg5:number):Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopAIGeneration(arg1:number):Promise<void>;

export function StopForwardConfig(arg1:number):Promise<void>;

export function StopK8sPodLogs(arg1:string):Promise<void>;

export function SwitchConversation(arg1:number):Promise<Array<app.ConversationDisplayMessage>>;

export function TestDatabaseConnection(arg1:string,arg2:string,arg3:string):Promise<void>;

export function TestKafkaConnection(arg1:string,arg2:string,arg3:string):Promise<void>;

export function TestMongoDBConnection(arg1:string,arg2:string,arg3:string):Promise<void>;

export function TestPolicyRule(arg1:app.PolicyTestRequest):Promise<app.PolicyTestResult>;

export function TestRedisConnection(arg1:string,arg2:string,arg3:string):Promise<void>;

export function TestSSHConnection(arg1:string,arg2:string,arg3:string):Promise<void>;

export function TestWebDAVConfig(arg1:app.WebDAVSaveInput):Promise<void>;

export function UninstallExtension(arg1:string,arg2:boolean):Promise<void>;

export function UpdateAIProvider(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:number,arg8:number,arg9:boolean,arg10:string):Promise<void>;

export function UpdateAsset(arg1:asset_entity.Asset):Promise<void>;

export function UpdateAssetPassword(arg1:number,arg2:string):Promise<void>;

export function UpdateConversationTitle(arg1:number,arg2:string):Promise<void>;

export function UpdateCredential(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<credential_entity.Credential>;

export function UpdateCredentialPassphrase(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateCredentialPassword(arg1:number,arg2:string):Promise<void>;

export function UpdateForwardConfig(arg1:number,arg2:string,arg3:number,arg4:Array<forward_entity.ForwardRule>):Promise<forward_entity.ForwardConfig>;

export function UpdateGroup(arg1:group_entity.Group):Promise<void>;

export function UpdatePolicyGroup(arg1:policy_group_entity.PolicyGroup):Promise<void>;

export function UpdateSnippet(arg1:snippet_svc.UpdateReq):Promise<snippet_entity.Snippet>;

export function WaitAIFlushAck():Promise<any>;

export function WaitGitHubDeviceAuth(arg1:string,arg2:number):Promise<string>;

export function WriteSSH(arg1:string,arg2:string):Promise<void>;

export function WriteTableExportFile(arg1:string,arg2:string,arg3:app.TableExportWriteOptions):Promise<void>;
