// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CallExtensionAction(arg1, arg2, arg3) {
  return window['go']['app']['App']['CallExtensionAction'](arg1, arg2, arg3);
}

export function CallExtensionTool(arg1, arg2, arg3) {
  return window['go']['app']['App']['CallExtensionTool'](arg1, arg2, arg3);
}

export function CancelExtensionAction(arg1) {
  return window['go']['app']['App']['CancelExtensionAction'](arg1);
}

export function CancelGitHubAuth() {
  return window['go']['app']['App']['CancelGitHubAuth']();
}

export function CancelSSHConnect(arg1) {
  return window['go']['app']['App']['CancelSSHConnect'](arg1);
}

export function CancelTest(arg1) {
  return window['go']['app']['App']['CancelTest'](arg1);
}

export function ChangeSSHDirectory(arg1, arg2) {
  return window['go']['app']['App']['ChangeSSHDirectory'](arg1, arg2);
}

export function CheckForUpdate() {
  return window['go']['app']['App']['CheckForUpdate']();
}

export function Cleanup() {
  return window['go']['app']['App']['Cleanup']();
}

export function ClearGitHubToken() {
  return window['go']['app']['App']['ClearGitHubToken']();
}

export function ClearQueuedAIMessages(arg1) {
  return window['go']['app']['App']['ClearQueuedAIMessages'](arg1);
}

export function ClearWebDAVConfig() {
  return window['go']['app']['App']['ClearWebDAVConfig']();
}

export function ConnectSSH(arg1) {
  return window['go']['app']['App']['ConnectSSH'](arg1);
}

export function ConnectSSHAsync(arg1) {
  return window['go']['app']['App']['ConnectSSHAsync'](arg1);
}

export function CopyPolicyGroup(arg1, arg2) {
  return window['go']['app']['App']['CopyPolicyGroup'](arg1, arg2);
}

export function CreateAIProvider(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['app']['App']['CreateAIProvider'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function CreateAsset(arg1) {
  return window['go']['app']['App']['CreateAsset'](arg1);
}

export function CreateConversation() {
  return window['go']['app']['App']['CreateConversation']();
}

export function CreateForwardConfig(arg1, arg2, arg3) {
  return window['go']['app']['App']['CreateForwardConfig'](arg1, arg2, arg3);
}

export function CreateGroup(arg1) {
  return window['go']['app']['App']['CreateGroup'](arg1);
}

export function CreatePasswordCredential(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['CreatePasswordCredential'](arg1, arg2, arg3, arg4);
}

export function CreatePolicyGroup(arg1) {
  return window['go']['app']['App']['CreatePolicyGroup'](arg1);
}

export function CreateSnippet(arg1) {
  return window['go']['app']['App']['CreateSnippet'](arg1);
}

export function DeleteAIProvider(arg1) {
  return window['go']['app']['App']['DeleteAIProvider'](arg1);
}

export function DeleteAsset(arg1) {
  return window['go']['app']['App']['DeleteAsset'](arg1);
}

export function DeleteConversation(arg1) {
  return window['go']['app']['App']['DeleteConversation'](arg1);
}

export function DeleteCredential(arg1) {
  return window['go']['app']['App']['DeleteCredential'](arg1);
}

export function DeleteForwardConfig(arg1) {
  return window['go']['app']['App']['DeleteForwardConfig'](arg1);
}

export function DeleteGroup(arg1, arg2) {
  return window['go']['app']['App']['DeleteGroup'](arg1, arg2);
}

export function DeletePolicyGroup(arg1) {
  return window['go']['app']['App']['DeletePolicyGroup'](arg1);
}

export function DeleteSnippet(arg1) {
  return window['go']['app']['App']['DeleteSnippet'](arg1);
}

export function DetectOpsctl() {
  return window['go']['app']['App']['DetectOpsctl']();
}

export function DetectSkills() {
  return window['go']['app']['App']['DetectSkills']();
}

export function DisableExtension(arg1) {
  return window['go']['app']['App']['DisableExtension'](arg1);
}

export function DisconnectSSH(arg1) {
  return window['go']['app']['App']['DisconnectSSH'](arg1);
}

export function DownloadAndInstallUpdate(arg1) {
  return window['go']['app']['App']['DownloadAndInstallUpdate'](arg1);
}

export function DrainAIFlushAck() {
  return window['go']['app']['App']['DrainAIFlushAck']();
}

export function DuplicateSnippet(arg1) {
  return window['go']['app']['App']['DuplicateSnippet'](arg1);
}

export function EnableExtension(arg1) {
  return window['go']['app']['App']['EnableExtension'](arg1);
}

export function EnableSSHSync(arg1) {
  return window['go']['app']['App']['EnableSSHSync'](arg1);
}

export function EncryptPassword(arg1) {
  return window['go']['app']['App']['EncryptPassword'](arg1);
}

export function ExecuteImportFile(arg1, arg2, arg3) {
  return window['go']['app']['App']['ExecuteImportFile'](arg1, arg2, arg3);
}

export function ExecuteMongo(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['ExecuteMongo'](arg1, arg2, arg3, arg4, arg5);
}

export function ExecuteRedis(arg1, arg2, arg3) {
  return window['go']['app']['App']['ExecuteRedis'](arg1, arg2, arg3);
}

export function ExecuteRedisArgs(arg1, arg2, arg3) {
  return window['go']['app']['App']['ExecuteRedisArgs'](arg1, arg2, arg3);
}

export function ExecuteSQL(arg1, arg2, arg3) {
  return window['go']['app']['App']['ExecuteSQL'](arg1, arg2, arg3);
}

export function ExecuteSQLPaged(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['ExecuteSQLPaged'](arg1, arg2, arg3, arg4, arg5);
}

export function ExecuteTableImport(arg1, arg2, arg3) {
  return window['go']['app']['App']['ExecuteTableImport'](arg1, arg2, arg3);
}

export function ExportData() {
  return window['go']['app']['App']['ExportData']();
}

export function ExportToFile(arg1, arg2) {
  return window['go']['app']['App']['ExportToFile'](arg1, arg2);
}

export function ExportToGist(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ExportToGist'](arg1, arg2, arg3, arg4);
}

export function ExportToWebDAV(arg1, arg2) {
  return window['go']['app']['App']['ExportToWebDAV'](arg1, arg2);
}

export function FetchAIModels(arg1, arg2, arg3) {
  return window['go']['app']['App']['FetchAIModels'](arg1, arg2, arg3);
}

export function ForceUninstallExtension(arg1, arg2) {
  return window['go']['app']['App']['ForceUninstallExtension'](arg1, arg2);
}

export function GenerateSSHKey(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['GenerateSSHKey'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetActiveAIProvider() {
  return window['go']['app']['App']['GetActiveAIProvider']();
}

export function GetAppVersion() {
  return window['go']['app']['App']['GetAppVersion']();
}

export function GetAsset(arg1) {
  return window['go']['app']['App']['GetAsset'](arg1);
}

export function GetAssetPassword(arg1) {
  return window['go']['app']['App']['GetAssetPassword'](arg1);
}

export function GetAvailableAssetTypes() {
  return window['go']['app']['App']['GetAvailableAssetTypes']();
}

export function GetAvailableMirrors() {
  return window['go']['app']['App']['GetAvailableMirrors']();
}

export function GetBugReportInfo() {
  return window['go']['app']['App']['GetBugReportInfo']();
}

export function GetCredentialPublicKey(arg1) {
  return window['go']['app']['App']['GetCredentialPublicKey'](arg1);
}

export function GetCredentialUsage(arg1) {
  return window['go']['app']['App']['GetCredentialUsage'](arg1);
}

export function GetCurrentConversationID() {
  return window['go']['app']['App']['GetCurrentConversationID']();
}

export function GetDataDir() {
  return window['go']['app']['App']['GetDataDir']();
}

export function GetDebugMode() {
  return window['go']['app']['App']['GetDebugMode']();
}

export function GetDecryptedExtensionConfig(arg1, arg2) {
  return window['go']['app']['App']['GetDecryptedExtensionConfig'](arg1, arg2);
}

export function GetDefaultPolicy(arg1) {
  return window['go']['app']['App']['GetDefaultPolicy'](arg1);
}

export function GetDownloadMirror() {
  return window['go']['app']['App']['GetDownloadMirror']();
}

export function GetExtensionDetail(arg1) {
  return window['go']['app']['App']['GetExtensionDetail'](arg1);
}

export function GetExtensionManifest(arg1) {
  return window['go']['app']['App']['GetExtensionManifest'](arg1);
}

export function GetGitHubToken() {
  return window['go']['app']['App']['GetGitHubToken']();
}

export function GetGitHubUser(arg1) {
  return window['go']['app']['App']['GetGitHubUser'](arg1);
}

export function GetGroup(arg1) {
  return window['go']['app']['App']['GetGroup'](arg1);
}

export function GetK8sClusterInfo(arg1) {
  return window['go']['app']['App']['GetK8sClusterInfo'](arg1);
}

export function GetK8sNamespaceConfigMaps(arg1, arg2) {
  return window['go']['app']['App']['GetK8sNamespaceConfigMaps'](arg1, arg2);
}

export function GetK8sNamespaceDeployments(arg1, arg2) {
  return window['go']['app']['App']['GetK8sNamespaceDeployments'](arg1, arg2);
}

export function GetK8sNamespacePods(arg1, arg2) {
  return window['go']['app']['App']['GetK8sNamespacePods'](arg1, arg2);
}

export function GetK8sNamespaceResources(arg1, arg2) {
  return window['go']['app']['App']['GetK8sNamespaceResources'](arg1, arg2);
}

export function GetK8sNamespaceSecrets(arg1, arg2) {
  return window['go']['app']['App']['GetK8sNamespaceSecrets'](arg1, arg2);
}

export function GetK8sNamespaceServices(arg1, arg2) {
  return window['go']['app']['App']['GetK8sNamespaceServices'](arg1, arg2);
}

export function GetK8sPodDetail(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetK8sPodDetail'](arg1, arg2, arg3);
}

export function GetLanguage() {
  return window['go']['app']['App']['GetLanguage']();
}

export function GetModelDefaults(arg1) {
  return window['go']['app']['App']['GetModelDefaults'](arg1);
}

export function GetOpsctlInstallDir() {
  return window['go']['app']['App']['GetOpsctlInstallDir']();
}

export function GetPluginReferenceDir() {
  return window['go']['app']['App']['GetPluginReferenceDir']();
}

export function GetSSHPoolConnections() {
  return window['go']['app']['App']['GetSSHPoolConnections']();
}

export function GetSSHSyncState(arg1) {
  return window['go']['app']['App']['GetSSHSyncState'](arg1);
}

export function GetSkillPreview() {
  return window['go']['app']['App']['GetSkillPreview']();
}

export function GetSnippet(arg1) {
  return window['go']['app']['App']['GetSnippet'](arg1);
}

export function GetSnippetLastAssets(arg1) {
  return window['go']['app']['App']['GetSnippetLastAssets'](arg1);
}

export function GetStoredGitHubUser() {
  return window['go']['app']['App']['GetStoredGitHubUser']();
}

export function GetSystemStatus() {
  return window['go']['app']['App']['GetSystemStatus']();
}

export function GetUpdateChannel() {
  return window['go']['app']['App']['GetUpdateChannel']();
}

export function GetWebDAVConfig() {
  return window['go']['app']['App']['GetWebDAVConfig']();
}

export function ImportFromGist(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ImportFromGist'](arg1, arg2, arg3, arg4);
}

export function ImportFromWebDAV(arg1, arg2, arg3) {
  return window['go']['app']['App']['ImportFromWebDAV'](arg1, arg2, arg3);
}

export function ImportSSHConfigSelected(arg1, arg2) {
  return window['go']['app']['App']['ImportSSHConfigSelected'](arg1, arg2);
}

export function ImportSSHKeyFile(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ImportSSHKeyFile'](arg1, arg2, arg3, arg4);
}

export function ImportSSHKeyPEM(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['ImportSSHKeyPEM'](arg1, arg2, arg3, arg4, arg5);
}

export function ImportTabbySelected(arg1, arg2, arg3) {
  return window['go']['app']['App']['ImportTabbySelected'](arg1, arg2, arg3);
}

export function InitAIProvider() {
  return window['go']['app']['App']['InitAIProvider']();
}

export function InstallExtension() {
  return window['go']['app']['App']['InstallExtension']();
}

export function InstallExtensionFromDirectory() {
  return window['go']['app']['App']['InstallExtensionFromDirectory']();
}

export function InstallOpsctl(arg1) {
  return window['go']['app']['App']['InstallOpsctl'](arg1);
}

export function InstallSkills() {
  return window['go']['app']['App']['InstallSkills']();
}

export function KafkaAlterTopicConfig(arg1) {
  return window['go']['app']['App']['KafkaAlterTopicConfig'](arg1);
}

export function KafkaBrowseMessages(arg1) {
  return window['go']['app']['App']['KafkaBrowseMessages'](arg1);
}

export function KafkaCheckSchemaCompatibility(arg1) {
  return window['go']['app']['App']['KafkaCheckSchemaCompatibility'](arg1);
}

export function KafkaClusterOverview(arg1) {
  return window['go']['app']['App']['KafkaClusterOverview'](arg1);
}

export function KafkaCreateACL(arg1) {
  return window['go']['app']['App']['KafkaCreateACL'](arg1);
}

export function KafkaCreateConnector(arg1) {
  return window['go']['app']['App']['KafkaCreateConnector'](arg1);
}

export function KafkaCreateTopic(arg1) {
  return window['go']['app']['App']['KafkaCreateTopic'](arg1);
}

export function KafkaDeleteACL(arg1) {
  return window['go']['app']['App']['KafkaDeleteACL'](arg1);
}

export function KafkaDeleteConnector(arg1, arg2, arg3) {
  return window['go']['app']['App']['KafkaDeleteConnector'](arg1, arg2, arg3);
}

export function KafkaDeleteConsumerGroup(arg1, arg2) {
  return window['go']['app']['App']['KafkaDeleteConsumerGroup'](arg1, arg2);
}

export function KafkaDeleteRecords(arg1) {
  return window['go']['app']['App']['KafkaDeleteRecords'](arg1);
}

export function KafkaDeleteSchema(arg1) {
  return window['go']['app']['App']['KafkaDeleteSchema'](arg1);
}

export function KafkaDeleteTopic(arg1, arg2) {
  return window['go']['app']['App']['KafkaDeleteTopic'](arg1, arg2);
}

export function KafkaGetBrokerConfig(arg1, arg2) {
  return window['go']['app']['App']['KafkaGetBrokerConfig'](arg1, arg2);
}

export function KafkaGetConnector(arg1, arg2, arg3) {
  return window['go']['app']['App']['KafkaGetConnector'](arg1, arg2, arg3);
}

export function KafkaGetConsumerGroup(arg1, arg2) {
  return window['go']['app']['App']['KafkaGetConsumerGroup'](arg1, arg2);
}

export function KafkaGetSchema(arg1, arg2, arg3) {
  return window['go']['app']['App']['KafkaGetSchema'](arg1, arg2, arg3);
}

export function KafkaGetSchemaSubjectVersions(arg1, arg2) {
  return window['go']['app']['App']['KafkaGetSchemaSubjectVersions'](arg1, arg2);
}

export function KafkaGetTopic(arg1, arg2) {
  return window['go']['app']['App']['KafkaGetTopic'](arg1, arg2);
}

export function KafkaIncreasePartitions(arg1) {
  return window['go']['app']['App']['KafkaIncreasePartitions'](arg1);
}

export function KafkaListACLs(arg1) {
  return window['go']['app']['App']['KafkaListACLs'](arg1);
}

export function KafkaListBrokers(arg1) {
  return window['go']['app']['App']['KafkaListBrokers'](arg1);
}

export function KafkaListClusterConfigs(arg1) {
  return window['go']['app']['App']['KafkaListClusterConfigs'](arg1);
}

export function KafkaListConnectClusters(arg1) {
  return window['go']['app']['App']['KafkaListConnectClusters'](arg1);
}

export function KafkaListConnectors(arg1) {
  return window['go']['app']['App']['KafkaListConnectors'](arg1);
}

export function KafkaListConsumerGroups(arg1) {
  return window['go']['app']['App']['KafkaListConsumerGroups'](arg1);
}

export function KafkaListSchemaSubjects(arg1) {
  return window['go']['app']['App']['KafkaListSchemaSubjects'](arg1);
}

export function KafkaListTopics(arg1) {
  return window['go']['app']['App']['KafkaListTopics'](arg1);
}

export function KafkaPauseConnector(arg1, arg2, arg3) {
  return window['go']['app']['App']['KafkaPauseConnector'](arg1, arg2, arg3);
}

export function KafkaProduceMessage(arg1) {
  return window['go']['app']['App']['KafkaProduceMessage'](arg1);
}

export function KafkaRegisterSchema(arg1) {
  return window['go']['app']['App']['KafkaRegisterSchema'](arg1);
}

export function KafkaResetConsumerGroupOffset(arg1) {
  return window['go']['app']['App']['KafkaResetConsumerGroupOffset'](arg1);
}

export function KafkaRestartConnector(arg1) {
  return window['go']['app']['App']['KafkaRestartConnector'](arg1);
}

export function KafkaResumeConnector(arg1, arg2, arg3) {
  return window['go']['app']['App']['KafkaResumeConnector'](arg1, arg2, arg3);
}

export function KafkaUpdateConnectorConfig(arg1) {
  return window['go']['app']['App']['KafkaUpdateConnectorConfig'](arg1);
}

export function ListAIProviders() {
  return window['go']['app']['App']['ListAIProviders']();
}

export function ListAssets(arg1, arg2) {
  return window['go']['app']['App']['ListAssets'](arg1, arg2);
}

export function ListAuditLogs(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['app']['App']['ListAuditLogs'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ListAuditSessions(arg1) {
  return window['go']['app']['App']['ListAuditSessions'](arg1);
}

export function ListBackupGists(arg1) {
  return window['go']['app']['App']['ListBackupGists'](arg1);
}

export function ListConversations() {
  return window['go']['app']['App']['ListConversations']();
}

export function ListCredentials() {
  return window['go']['app']['App']['ListCredentials']();
}

export function ListCredentialsByType(arg1) {
  return window['go']['app']['App']['ListCredentialsByType'](arg1);
}

export function ListForwardConfigs() {
  return window['go']['app']['App']['ListForwardConfigs']();
}

export function ListGroups() {
  return window['go']['app']['App']['ListGroups']();
}

export function ListInstalledExtensions() {
  return window['go']['app']['App']['ListInstalledExtensions']();
}

export function ListLocalSSHKeys() {
  return window['go']['app']['App']['ListLocalSSHKeys']();
}

export function ListMongoCollections(arg1, arg2) {
  return window['go']['app']['App']['ListMongoCollections'](arg1, arg2);
}

export function ListMongoDatabases(arg1) {
  return window['go']['app']['App']['ListMongoDatabases'](arg1);
}

export function ListPolicyGroups(arg1) {
  return window['go']['app']['App']['ListPolicyGroups'](arg1);
}

export function ListSnippetCategories() {
  return window['go']['app']['App']['ListSnippetCategories']();
}

export function ListSnippets(arg1) {
  return window['go']['app']['App']['ListSnippets'](arg1);
}

export function ListWebDAVBackups() {
  return window['go']['app']['App']['ListWebDAVBackups']();
}

export function LoadConversationMessages(arg1) {
  return window['go']['app']['App']['LoadConversationMessages'](arg1);
}

export function MoveAsset(arg1, arg2) {
  return window['go']['app']['App']['MoveAsset'](arg1, arg2);
}

export function MoveGroup(arg1, arg2) {
  return window['go']['app']['App']['MoveGroup'](arg1, arg2);
}

export function OnSecondInstanceLaunch() {
  return window['go']['app']['App']['OnSecondInstanceLaunch']();
}

export function OpenDirectory(arg1) {
  return window['go']['app']['App']['OpenDirectory'](arg1);
}

export function OpenLogsDir() {
  return window['go']['app']['App']['OpenLogsDir']();
}

export function PreviewGistBackup(arg1, arg2, arg3) {
  return window['go']['app']['App']['PreviewGistBackup'](arg1, arg2, arg3);
}

export function PreviewImportFile(arg1, arg2) {
  return window['go']['app']['App']['PreviewImportFile'](arg1, arg2);
}

export function PreviewSSHConfig() {
  return window['go']['app']['App']['PreviewSSHConfig']();
}

export function PreviewTabbyConfig() {
  return window['go']['app']['App']['PreviewTabbyConfig']();
}

export function QueueAIMessage(arg1, arg2, arg3) {
  return window['go']['app']['App']['QueueAIMessage'](arg1, arg2, arg3);
}

export function RecordSnippetUse(arg1) {
  return window['go']['app']['App']['RecordSnippetUse'](arg1);
}

export function RedisClientList(arg1) {
  return window['go']['app']['App']['RedisClientList'](arg1);
}

export function RedisCommandHistory(arg1, arg2) {
  return window['go']['app']['App']['RedisCommandHistory'](arg1, arg2);
}

export function RedisDeleteKeys(arg1, arg2, arg3) {
  return window['go']['app']['App']['RedisDeleteKeys'](arg1, arg2, arg3);
}

export function RedisEncodeValue(arg1, arg2) {
  return window['go']['app']['App']['RedisEncodeValue'](arg1, arg2);
}

export function RedisFormatValue(arg1, arg2) {
  return window['go']['app']['App']['RedisFormatValue'](arg1, arg2);
}

export function RedisGetKeyDetail(arg1) {
  return window['go']['app']['App']['RedisGetKeyDetail'](arg1);
}

export function RedisHashDelete(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['RedisHashDelete'](arg1, arg2, arg3, arg4);
}

export function RedisHashSet(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['RedisHashSet'](arg1, arg2, arg3, arg4, arg5);
}

export function RedisListDatabases(arg1) {
  return window['go']['app']['App']['RedisListDatabases'](arg1);
}

export function RedisListDelete(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['RedisListDelete'](arg1, arg2, arg3, arg4);
}

export function RedisListPush(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['RedisListPush'](arg1, arg2, arg3, arg4);
}

export function RedisListSet(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['RedisListSet'](arg1, arg2, arg3, arg4, arg5);
}

export function RedisPersistKey(arg1, arg2, arg3) {
  return window['go']['app']['App']['RedisPersistKey'](arg1, arg2, arg3);
}

export function RedisRenameKey(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['RedisRenameKey'](arg1, arg2, arg3, arg4);
}

export function RedisScanKeys(arg1) {
  return window['go']['app']['App']['RedisScanKeys'](arg1);
}

export function RedisSetAdd(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['RedisSetAdd'](arg1, arg2, arg3, arg4);
}

export function RedisSetKeyTTL(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['RedisSetKeyTTL'](arg1, arg2, arg3, arg4);
}

export function RedisSetRemove(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['RedisSetRemove'](arg1, arg2, arg3, arg4);
}

export function RedisSetStringValue(arg1) {
  return window['go']['app']['App']['RedisSetStringValue'](arg1);
}

export function RedisSlowLog(arg1, arg2) {
  return window['go']['app']['App']['RedisSlowLog'](arg1, arg2);
}

export function RedisStreamAdd(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['RedisStreamAdd'](arg1, arg2, arg3, arg4, arg5);
}

export function RedisStreamDelete(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['RedisStreamDelete'](arg1, arg2, arg3, arg4);
}

export function RedisZSetAdd(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['RedisZSetAdd'](arg1, arg2, arg3, arg4, arg5);
}

export function RedisZSetRemove(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['RedisZSetRemove'](arg1, arg2, arg3, arg4);
}

export function ReloadExtensions() {
  return window['go']['app']['App']['ReloadExtensions']();
}

export function RemoveQueuedAIMessage(arg1, arg2) {
  return window['go']['app']['App']['RemoveQueuedAIMessage'](arg1, arg2);
}

export function ReorderAsset(arg1, arg2, arg3) {
  return window['go']['app']['App']['ReorderAsset'](arg1, arg2, arg3);
}

export function ReorderGroup(arg1, arg2, arg3) {
  return window['go']['app']['App']['ReorderGroup'](arg1, arg2, arg3);
}

export function ResizeSSH(arg1, arg2, arg3) {
  return window['go']['app']['App']['ResizeSSH'](arg1, arg2, arg3);
}

export function RespondAIApproval(arg1, arg2) {
  return window['go']['app']['App']['RespondAIApproval'](arg1, arg2);
}

export function RespondAuthChallenge(arg1, arg2) {
  return window['go']['app']['App']['RespondAuthChallenge'](arg1, arg2);
}

export function RespondHostKeyVerify(arg1, arg2) {
  return window['go']['app']['App']['RespondHostKeyVerify'](arg1, arg2);
}

export function RespondOpsctlApproval(arg1, arg2) {
  return window['go']['app']['App']['RespondOpsctlApproval'](arg1, arg2);
}

export function RespondPermission(arg1, arg2) {
  return window['go']['app']['App']['RespondPermission'](arg1, arg2);
}

export function SFTPCancelTransfer(arg1) {
  return window['go']['app']['App']['SFTPCancelTransfer'](arg1);
}

export function SFTPDelete(arg1, arg2, arg3) {
  return window['go']['app']['App']['SFTPDelete'](arg1, arg2, arg3);
}

export function SFTPDownload(arg1, arg2) {
  return window['go']['app']['App']['SFTPDownload'](arg1, arg2);
}

export function SFTPDownloadDir(arg1, arg2) {
  return window['go']['app']['App']['SFTPDownloadDir'](arg1, arg2);
}

export function SFTPGetwd(arg1) {
  return window['go']['app']['App']['SFTPGetwd'](arg1);
}

export function SFTPListDir(arg1, arg2) {
  return window['go']['app']['App']['SFTPListDir'](arg1, arg2);
}

export function SFTPUpload(arg1, arg2) {
  return window['go']['app']['App']['SFTPUpload'](arg1, arg2);
}

export function SFTPUploadDir(arg1, arg2) {
  return window['go']['app']['App']['SFTPUploadDir'](arg1, arg2);
}

export function SFTPUploadFile(arg1, arg2, arg3) {
  return window['go']['app']['App']['SFTPUploadFile'](arg1, arg2, arg3);
}

export function SaveConversationMessages(arg1, arg2) {
  return window['go']['app']['App']['SaveConversationMessages'](arg1, arg2);
}

export function SaveGitHubToken(arg1, arg2) {
  return window['go']['app']['App']['SaveGitHubToken'](arg1, arg2);
}

export function SaveWebDAVConfig(arg1) {
  return window['go']['app']['App']['SaveWebDAVConfig'](arg1);
}

export function SelectImportFile() {
  return window['go']['app']['App']['SelectImportFile']();
}

export function SelectSSHKeyFile() {
  return window['go']['app']['App']['SelectSSHKeyFile']();
}

export function SelectTableExportFile(arg1, arg2, arg3) {
  return window['go']['app']['App']['SelectTableExportFile'](arg1, arg2, arg3);
}

export function SendAIMessage(arg1, arg2, arg3) {
  return window['go']['app']['App']['SendAIMessage'](arg1, arg2, arg3);
}

export function SetActiveAIProvider(arg1) {
  return window['go']['app']['App']['SetActiveAIProvider'](arg1);
}

export function SetDebugMode(arg1) {
  return window['go']['app']['App']['SetDebugMode'](arg1);
}

export function SetDownloadMirror(arg1) {
  return window['go']['app']['App']['SetDownloadMirror'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['app']['App']['SetLanguage'](arg1);
}

export function SetSnippetLastAssets(arg1, arg2) {
  return window['go']['app']['App']['SetSnippetLastAssets'](arg1, arg2);
}

export function SetUpdateChannel(arg1) {
  return window['go']['app']['App']['SetUpdateChannel'](arg1);
}

export function SplitSSH(arg1, arg2, arg3) {
  return window['go']['app']['App']['SplitSSH'](arg1, arg2, arg3);
}

export function StartForwardConfig(arg1) {
  return window['go']['app']['App']['StartForwardConfig'](arg1);
}

export function StartGitHubDeviceFlow() {
  return window['go']['app']['App']['StartGitHubDeviceFlow']();
}

export function StartK8sPodLogs(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['StartK8sPodLogs'](arg1, arg2, arg3, arg4, arg5);
}

export function Startup(arg1) {
  return window['go']['app']['App']['Startup'](arg1);
}

export function StopAIGeneration(arg1) {
  return window['go']['app']['App']['StopAIGeneration'](arg1);
}

export function StopForwardConfig(arg1) {
  return window['go']['app']['App']['StopForwardConfig'](arg1);
}

export function StopK8sPodLogs(arg1) {
  return window['go']['app']['App']['StopK8sPodLogs'](arg1);
}

export function SwitchConversation(arg1) {
  return window['go']['app']['App']['SwitchConversation'](arg1);
}

export function TestDatabaseConnection(arg1, arg2, arg3) {
  return window['go']['app']['App']['TestDatabaseConnection'](arg1, arg2, arg3);
}

export function TestKafkaConnection(arg1, arg2, arg3) {
  return window['go']['app']['App']['TestKafkaConnection'](arg1, arg2, arg3);
}

export function TestMongoDBConnection(arg1, arg2, arg3) {
  return window['go']['app']['App']['TestMongoDBConnection'](arg1, arg2, arg3);
}

export function TestPolicyRule(arg1) {
  return window['go']['app']['App']['TestPolicyRule'](arg1);
}

export function TestRedisConnection(arg1, arg2, arg3) {
  return window['go']['app']['App']['TestRedisConnection'](arg1, arg2, arg3);
}

export function TestSSHConnection(arg1, arg2, arg3) {
  return window['go']['app']['App']['TestSSHConnection'](arg1, arg2, arg3);
}

export function TestWebDAVConfig(arg1) {
  return window['go']['app']['App']['TestWebDAVConfig'](arg1);
}

export function UninstallExtension(arg1, arg2) {
  return window['go']['app']['App']['UninstallExtension'](arg1, arg2);
}

export function UpdateAIProvider(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['app']['App']['UpdateAIProvider'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function UpdateAsset(arg1) {
  return window['go']['app']['App']['UpdateAsset'](arg1);
}

export function UpdateAssetPassword(arg1, arg2) {
  return window['go']['app']['App']['UpdateAssetPassword'](arg1, arg2);
}

export function UpdateConversationTitle(arg1, arg2) {
  return window['go']['app']['App']['UpdateConversationTitle'](arg1, arg2);
}

export function UpdateCredential(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['UpdateCredential'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateCredentialPassphrase(arg1, arg2, arg3) {
  return window['go']['app']['App']['UpdateCredentialPassphrase'](arg1, arg2, arg3);
}

export function UpdateCredentialPassword(arg1, arg2) {
  return window['go']['app']['App']['UpdateCredentialPassword'](arg1, arg2);
}

export function UpdateForwardConfig(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['UpdateForwardConfig'](arg1, arg2, arg3, arg4);
}

export function UpdateGroup(arg1) {
  return window['go']['app']['App']['UpdateGroup'](arg1);
}

export function UpdatePolicyGroup(arg1) {
  return window['go']['app']['App']['UpdatePolicyGroup'](arg1);
}

export function UpdateSnippet(arg1) {
  return window['go']['app']['App']['UpdateSnippet'](arg1);
}

export function WaitAIFlushAck() {
  return window['go']['app']['App']['WaitAIFlushAck']();
}

export function WaitGitHubDeviceAuth(arg1, arg2) {
  return window['go']['app']['App']['WaitGitHubDeviceAuth'](arg1, arg2);
}

export function WriteSSH(arg1, arg2) {
  return window['go']['app']['App']['WriteSSH'](arg1, arg2);
}

export function WriteTableExportFile(arg1, arg2, arg3) {
  return window['go']['app']['App']['WriteTableExportFile'](arg1, arg2, arg3);
}
